import { AnimationReferenceMetadata } from '@angular/animations';
export declare const bounce: AnimationReferenceMetadata;
export declare const flash: AnimationReferenceMetadata;
export declare const pulse: AnimationReferenceMetadata;
export declare const rubberBand: AnimationReferenceMetadata;
export declare const shake: AnimationReferenceMetadata;
export declare const swing: AnimationReferenceMetadata;
export declare const tada: AnimationReferenceMetadata;
export declare const wobble: AnimationReferenceMetadata;
export declare const jello: AnimationReferenceMetadata;
