import { AnimationReferenceMetadata } from '@angular/animations';
export declare const bounceIn: AnimationReferenceMetadata;
export declare const bounceInDown: AnimationReferenceMetadata;
export declare const bounceInUp: AnimationReferenceMetadata;
export declare const bounceInLeft: AnimationReferenceMetadata;
export declare const bounceInRight: AnimationReferenceMetadata;
export declare const bounceOut: AnimationReferenceMetadata;
export declare const bounceOutDown: AnimationReferenceMetadata;
export declare const bounceOutUp: AnimationReferenceMetadata;
export declare const bounceOutLeft: AnimationReferenceMetadata;
export declare const bounceOutRight: AnimationReferenceMetadata;
