import { AnimationReferenceMetadata } from '@angular/animations';
export declare const rotateIn: AnimationReferenceMetadata;
export declare const rotateInDownLeft: AnimationReferenceMetadata;
export declare const rotateInDownRight: AnimationReferenceMetadata;
export declare const rotateInUpLeft: AnimationReferenceMetadata;
export declare const rotateInUpRight: AnimationReferenceMetadata;
export declare const rotateOut: AnimationReferenceMetadata;
export declare const rotateOutDownLeft: AnimationReferenceMetadata;
export declare const rotateOutDownRight: AnimationReferenceMetadata;
export declare const rotateOutUpLeft: AnimationReferenceMetadata;
export declare const rotateOutUpRight: AnimationReferenceMetadata;
